version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "stack-clients"
      - "stack-data-uploader"
      - "stack-manager"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directories:
      - "stack-clients"
      - "stack-data-uploader"
      - "stack-manager"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
