package com.cmclinnovations.stack.services;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.StringJoiner;

import org.apache.commons.lang3.exception.UncheckedException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.cmclinnovations.stack.clients.core.StackClient;
import com.cmclinnovations.stack.clients.utils.JsonHelper;
import com.cmclinnovations.stack.services.config.ServiceConfig;
import com.fasterxml.jackson.databind.JsonNode;
import com.github.dockerjava.api.command.InspectVolumeResponse;
import com.github.dockerjava.api.model.ContainerSpec;
import com.github.dockerjava.api.model.Mount;
import com.github.dockerjava.api.model.MountType;

public class KopiaService extends ContainerService {

    public static final String TYPE = "kopia";

    private static final String VOLUME_DIR = "/data/";
    private static final String KOPIA_PASSWORD_PATH = "/run/secrets/kopia_password";
    private static final String REPOSITORY_CONFIG = "/inputs/data/kopia/repository.config";
    private static final String SFTP_SSH_KEY_PATH = "/tmp/ssh_key";
    private static final String KNOWN_HOSTS_PATH = "/.ssh/known_hosts";
    private static final String ROOT_KNOWN_HOSTS_PATH = "/root" + KNOWN_HOSTS_PATH;
    private static final String SCHEDULED_SCRIPT_PATH = "/usr/local/bin/kopia-backup.sh";

    private static final String STORAGE_KEY = "storage";
    private static final String CREATE_REPO_ACTION = "create";
    private static final String CONNECT_REPO_ACTION = "connect";

    private final String storageType;
    private final String passwordFlag;
    private final JsonNode storageConfig;

    private static final Logger LOGGER = LoggerFactory.getLogger(KopiaService.class);

    public KopiaService(String stackName, ServiceConfig config) {
        super(stackName, config);
        JsonNode repoConfig = JsonHelper.readFile(REPOSITORY_CONFIG).get(STORAGE_KEY);
        this.storageConfig = repoConfig.get("config");
        this.storageType = repoConfig.get("type").asText();
        this.passwordFlag = "--password=\"$(cat " + KOPIA_PASSWORD_PATH + ")\"";
    }

    @Override
    public void doPreStartUpConfiguration() {
        // Mount all volumes on the stack (except kopia) for backups
        List<InspectVolumeResponse> volumes = super.getVolumes();
        List<Mount> mounts = new ArrayList<>();

        for (InspectVolumeResponse vol : volumes) {
            if (!vol.getName().endsWith(TYPE)) {
                // Remove stack name prefix (STACK_) from volume name
                String volName = vol.getName().substring(StackClient.getStackName().length() + 1);
                String destinationPath = VOLUME_DIR + volName;
                mounts.add(new Mount()
                        .withType(MountType.VOLUME) // Use Docker volume for named volumes
                        .withSource(volName)
                        .withTarget(destinationPath)
                        .withReadOnly(false));
            }
        }

        ContainerSpec containerSpec = super.getContainerSpec();
        containerSpec.withMounts(mounts);
    }

    @Override
    public void doFirstTimePostStartUpConfiguration() {
        this.genScheduledBackups();
    }

    private void genScheduledBackups() {
        LOGGER.info("Generating scheduled backup script...");
        String connectRepoCommand = this.genCreateOrConnectRepositoryCommand(CONNECT_REPO_ACTION);
        String createRepoCommand = this.genCreateOrConnectRepositoryCommand(CREATE_REPO_ACTION);
        String initSnapshotCommand = String.join(" ", TYPE, "snapshot", CREATE_REPO_ACTION, VOLUME_DIR,
                this.passwordFlag);
        String snapshotCommand = "kopia snapshot create --all " + this.passwordFlag;

        // Add a warning that this file is auto-generated
        StringJoiner scriptContents = new StringJoiner("\n")
                .add("#!/bin/bash")
                .add("# AUTO-GENERATED BY JAVA - DO NOT EDIT MANUALLY")
                .add("");

        if (this.storageType.equals("sftp") && this.requiresExternalSSH()) {
            scriptContents.add("eval `keychain --eval --agents ssh " + SFTP_SSH_KEY_PATH)
                    .add("");
        }

        scriptContents.add("if ! " + connectRepoCommand + "; then")
                .add("\t" + createRepoCommand)
                .add("\t" + connectRepoCommand)
                .add("\t" + initSnapshotCommand)
                .add("else")
                .add("\t" + snapshotCommand)
                .add("fi");

        super.sendFileContent(SCHEDULED_SCRIPT_PATH, scriptContents.toString().getBytes(StandardCharsets.UTF_8));
        // Requires executable permission for root user for the crone job
        super.createComplexCommand("chmod", "+x", SCHEDULED_SCRIPT_PATH)
                .withUser("root")
                .exec();
    }

    private String genCreateOrConnectRepositoryCommand(String action) {
        String storagePath = this.storageConfig.get("path").asText();
        StringJoiner command = new StringJoiner(" ")
                .add(TYPE).add("repository").add(action).add(this.storageType);
        switch (this.storageType) {
            case "sftp":
                this.genSSHKeyFile(this.storageConfig.get("keyfile").asText());

                String host = this.storageConfig.get("host").asText();
                String user = this.storageConfig.get("username").asText();
                if (action.equals(CREATE_REPO_ACTION) && !super.fileExists(ROOT_KNOWN_HOSTS_PATH)) {
                    super.executeCommand("sh", "-c", "ssh-keyscan -H " + host + " >> ~" + KNOWN_HOSTS_PATH);
                }
                command.add("--path=" + storagePath)
                        .add("--host=" + host)
                        .add("--username=" + user)
                        .add("--keyfile=" + SFTP_SSH_KEY_PATH)
                        .add("--known-hosts=" + ROOT_KNOWN_HOSTS_PATH);
                if (this.requiresExternalSSH()) {
                    command.add("--external");
                }
                break;
            case "filesystem":
                command.add("--path=" + storagePath);
                break;
            default:
                LOGGER.warn(
                        "Unsupported storage type '{}' for automatic stack setup. Please manually configure the storage",
                        this.storageType);
                break;
        }

        command.add(this.passwordFlag);
        return command.toString();
    }

    /**
     * Checks if the repository requires external SSH key access due to passphrase
     * protection.
     */
    private boolean requiresExternalSSH() {
        return this.storageConfig.has("externalSSH") && this.storageConfig.get("externalSSH").asBoolean();
    }

    /**
     * Generates an SSH key file in the Kopia container if it doesn't already exist.
     * 
     * @param keyFilePath Path to the SSH key file
     */
    private void genSSHKeyFile(String keyFilePath) {
        if (!super.fileExists(keyFilePath)) {
            try {
                super.sendFileContent(SFTP_SSH_KEY_PATH, Files.readAllBytes(Paths.get(keyFilePath)));
            } catch (IOException e) {
                throw new UncheckedException(e);
            }
        }
    }
}
