version: '3.8'
services:
  stack-manager:
    image: docker.cmclinnovations.com/stack-manager:1.0-SNAPSHOT
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
      # Add secret files here as Docker compose doesn't handle "secrets" well
      # Ensure all secret files are mapped to the /run/secrets/ directory
      # and are read only inside the container (add ":ro" on the end)
      - ./inputs/secrets:/run/secrets:ro
