version: '3.8'
services:
  stack-manager:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
      - "STACK_NAME=${STACK_NAME}"
    ports:
      - "5005:5005"
    networks:
      - stack

networks:
  stack:
    name: ${STACK_NAME}
    driver: overlay
    attachable: true
