version: '3.8'
services:
  stack-manager:
    image: docker.cmclinnovations.com/stack-manager:1.0-SNAPSHOT
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    environment:
      - "STACK_NAME=${STACK_NAME}"
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
      # Add secret files here as Docker compose doesn't handle "secrets" well
      # Ensure all secret files are mapped to the /run/secrets/ directory
      # and are read only inside the container (add ":ro" on the end)
      - ./inputs/secrets:/run/secrets:ro
      - scratch:/stack_scratch
    networks:
      - stack

volumes:
  scratch:
    name: ${STACK_NAME}_scratch
    labels:
      - com.docker.stack.namespace:${STACK_NAME}

networks:
  stack:
    name: ${STACK_NAME}
    driver: overlay
    attachable: true
