services:
  stack-client:
    secrets:
      - source: blazegraph
        target: /blazegraph
      - source: postgis
        target: /postgis
      - source: geoserver
        target: /geoserver
      - source: ontop
        target: /ontop
      - source: rdf4j
        target: /rdf4j

secrets:
  blazegraph:
    name: ${STACK_NAME}_blazegraph
    external: true
  postgis:
    name: ${STACK_NAME}_postgis
    external: true
  geoserver:
    name: ${STACK_NAME}_geoserver
    external: true
  ontop:
    name: ${STACK_NAME}_ontop
    external: true
  rdf4j:
    name: ${STACK_NAME}_rdf4j
    external: true
