version: '3.8'
services:
  stack-client:
    image: docker.cmclinnovations.com/stack-client${IMAGE_SUFFIX}:1.8.0-podman-SNAPSHOT
    secrets:
      - blazegraph_password
      - postgis_password
      - geoserver_password
      - source: blazegraph
        target: /blazegraph
      - source: ontop 
        target: /ontop
      - source: postgis 
        target: /postgis
      - source: geoserver 
        target: /geoserver
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
