version: '3.8'
services:
  stack-client:
    image: ghcr.io/cambridge-cares/stack-client${IMAGE_SUFFIX}:1.17.1-stack-building-thematic-vis-SNAPSHOT
    secrets:
      - blazegraph_password
      - postgis_password
      - geoserver_password
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
