version: '3.8'
services:
  stack-client:
    image: docker.cmclinnovations.com/stack-client:1.6.1
    configs:
      - postgis
      - geoserver
    secrets:
      - postgis_password
      - geoserver_password
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
