version: '3.8'
services:
  stack-client:
    image: docker.cmclinnovations.com/stack-client:1.0-SNAPSHOT
    build: .
    container_name: stack-client
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
      # Add secret files here as Docker compose doesn't handle "secrets" well
      # Ensure all secret files are mapped to the /run/secrets/ directory
      # and are read only inside the container (add ":ro" on the end)
      - ./inputs/secrets:/run/secrets:ro

  stack-client-lib:
    image: docker.cmclinnovations.com/stack-client-lib:1.0-SNAPSHOT
    build:
      context: .
      target: builder
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
