version: '3.8'
services:
  stack-client:
    configs:
      - blazegraph
      - postgis
      - geoserver
      - ontop
      - superset

configs:
  blazegraph:
    name: ${STACK_NAME}_blazegraph
    external: true
  postgis:
    name: ${STACK_NAME}_postgis
    external: true
  geoserver:
    name: ${STACK_NAME}_geoserver
    external: true
  ontop:
    name: ${STACK_NAME}_ontop
    external: true
  superset:
    name: ${STACK_NAME}_superset
    external: true
