version: '3.8'
services:
  stack-client:
    image: docker.cmclinnovations.com/stack-client${IMAGE_SUFFIX}:1.10.1-add-basic-endpoint-config-SNAPSHOT
    secrets:
      - blazegraph_password
      - postgis_password
      - geoserver_password
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
