services:
  stack-client:
    image: ghcr.io/cambridge-cares/stack-client${IMAGE_SUFFIX}:1.28.0-1201-SNAPSHOT
    secrets:
      - blazegraph_password
      - postgis_password
      - geoserver_password
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
