version: '3.8'
services:
  stack-client:
    image: docker.cmclinnovations.com/stack-client${IMAGE_SUFFIX}:1.9.0-582-dcat-ontop-SNAPSHOT
    configs:
      - blazegraph
      - ontop
      - postgis
      - geoserver
    secrets:
      - postgis_password
      - geoserver_password
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
