version: '3.8'
services:
  stack-data-uploader:
    image: docker.cmclinnovations.com/stack-data-uploader${IMAGE_SUFFIX}:1.8.0-add-superset-to-stack-SNAPSHOT
    configs:
      - blazegraph
      - postgis
      - geoserver
      - superset
    secrets:
      - blazegraph_password
      - postgis_password
      - geoserver_password
      - superset_password
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
