version: '3.8'
services:
  stack-data-uploader:
    image: ghcr.io/cambridge-cares/stack-data-uploader${IMAGE_SUFFIX}:1.15.1-stack-building-thematic-vis-SNAPSHOT
    secrets:
      - blazegraph_password
      - postgis_password
      - geoserver_password
    volumes:
      - ./inputs/data:/inputs/data:z
      - ./inputs/config:/inputs/config
