version: '3.8'
services:
  stack-data-uploader:
    image: ghcr.io/cambridge-cares/stack-data-uploader${IMAGE_SUFFIX}:1.29.1-hotfix-stack-clients-spring-nested-jars-SNAPSHOT
    secrets:
      - blazegraph_password
      - postgis_password
      - geoserver_password
    volumes:
      - ./inputs/data:/inputs/data:z
      - ./inputs/config:/inputs/config
