version: '3.8'
services:
  stack-data-uploader:
    image: docker.cmclinnovations.com/stack-data-uploader:1.5.2-376-error-thrown-when-trying-to-query-raster-data-in-the-stack-SNAPSHOT
    configs:
      - postgis
      - geoserver
    secrets:
      - postgis_password
      - geoserver_password
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
